package app

import (
	"errors"
	"flag"
	"fmt"
	"github.com/isnakolah/agent-profile/internal/state"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const launcherMarker = "# Generated by agent-profile; managed launcher."

func shellQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'" }
func launcherScript(provider, root string) string {
	return fmt.Sprintf("#!/bin/sh\nset -eu\nexport %s=%s\nexec %s \"$@\"\n", envName(provider), shellQuote(root), provider)
}
func launcherFiles(name string) (map[string]string, error) {
	bin, e := launcherDir()
	if e != nil {
		return nil, e
	}
	executable, e := os.Executable()
	if e != nil {
		return nil, e
	}
	result := map[string]string{}
	for _, suffix := range []string{"", "-codex", "-claude"} {
		tail := ""
		if suffix != "" {
			tail = " " + strings.TrimPrefix(suffix, "-")
		}
		result[filepath.Join(bin, name+suffix)] = fmt.Sprintf("#!/bin/sh\n%s\nexec %s run %s%s \"$@\"\n", launcherMarker, shellQuote(executable), shellQuote(name), tail)
	}
	return result, nil
}
func checkLaunchers(name string) error {
	if !validName(name) {
		return errors.New("profile names must start with a letter or digit and use letters, digits, dot, dash or underscore")
	}
	files, e := launcherFiles(name)
	if e != nil {
		return e
	}
	for path := range files {
		if b, err := os.ReadFile(path); err == nil {
			if !strings.Contains(string(b), launcherMarker) && !legacyLauncher(path, name, string(b)) {
				return fmt.Errorf("launcher collision at %s; choose another profile name", path)
			}
		} else if !os.IsNotExist(err) {
			return err
		}
		if info, err := os.Lstat(path); err == nil && info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("refusing launcher symlink %s", path)
		}
		if other, err := exec.LookPath(filepath.Base(path)); err == nil && other != path {
			return fmt.Errorf("command %s already exists at %s", filepath.Base(path), other)
		}
	}
	return nil
}
func launcherCommand(args []string) error {
	if len(args) < 2 || args[0] != "install" {
		return errors.New("usage: launcher install NAME [--apply]")
	}
	fs := flag.NewFlagSet("launcher install", flag.ContinueOnError)
	apply := fs.Bool("apply", false, "write managed launchers")
	if e := fs.Parse(args[2:]); e != nil {
		return e
	}
	if fs.NArg() != 0 {
		return errors.New("unexpected launcher arguments")
	}
	s, e := openStore()
	if e != nil {
		return e
	}
	defer s.close()
	if _, e = s.profile(args[1]); e != nil {
		return e
	}
	if e = checkLaunchers(args[1]); e != nil {
		return e
	}
	files, e := launcherFiles(args[1])
	if e != nil {
		return e
	}
	for path, content := range files {
		if !*apply {
			fmt.Printf("%s\n%s", path, content)
			continue
		}
		if e = state.Write(path, []byte(content), 0755); e != nil {
			return e
		}
		fmt.Println(path)
	}
	return nil
}

// Legacy launchers are adopted only when their entire content matches our old generator.
func legacyLauncher(path, name, content string) bool {
	root, err := dataRoot()
	if err != nil {
		return false
	}
	for _, kind := range []string{"codex", "claude"} {
		if filepath.Base(path) != name+"-"+kind {
			continue
		}
		dir := filepath.Join(root, "profiles", name, kind)
		old := fmt.Sprintf("#!/bin/sh\nset -eu\nexport %s=%q\nexec %s \"$@\"\n", envName(kind), dir, kind)
		return content == old || content == launcherScript(kind, dir)
	}
	return false
}
